[versions]
intellijGradle = "1.17.4"
json = "20251224"
kotlin = "2.3.10"
kotlinxSerializationJson = "1.10.0"
okhttp = "4.12.0"
versionCatalogUpdatePlugin = "1.0.1"
intellijPlatform = "2023.1.5"

[plugins]
intellij = { id = "org.jetbrains.intellij", version.ref = "intellijGradle" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdatePlugin" }

[libraries]
json = { module = "org.json:json", version.ref = "json" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
